# Generated by Django 5.0.6 on 2024-07-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HoopflixPortfolio', '0002_rename_name_contactform_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='Full_Name',
            new_name='FullName',
        ),
    ]
